import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='py-12 lg:px-36 lg:py-36'>
          <div>
            <h1 className='flex w-full justify-center text-5xl md:text-[85px] lg:text-[85px] font-extrabold text-blue-500 pb-5'> FarmaSya </h1>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
